# Docker Compose file to set up all of the docker instances
#
# @author khanhvy1703

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_MOVIE_TVSHOW_DB}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-scripts/setup.sql:/docker-entrypoint-initdb.d/1_movie_tvshow.sql
    networks:
      - backend

  app:
    build: ./back-end
    container_name: backend_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_MOVIE_TVSHOW_DB: ${MYSQL_MOVIE_TVSHOW_DB}
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:

